name: CI Github Pages

on:
  push:
    branches:
     - master
     
jobs:
  build-and-deploy:
    name: build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - name: 切换分支
        uses: actions/checkout@v3
        
      - name: 装包且构建
        run: |                               # 运行多条shell命令
          npm install -g yarn
          yarn install
          yarn build-storybook
          echo =========产物如下===================
          ls -lha
          echo ================build end======================
          
      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with: # 带着两个参数
          branch: gh-pages              # 部署提交分支
          folder: storybook-static      # 打包好的目录名称
